name: pdd_app_172
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  sqflite: ^2.3.0
  path: ^1.9.0
  path_provider: ^2.1.2
  cupertino_icons: ^1.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  # Assets должен быть строго под flutter с отступом в 2 пробела
  assets:
    - assets/data/questions.json
    - assets/data/rules.json
    - assets/data/signs.json
    - assets/images/
    - assets/icons/